id: PB2D9592D
initial_creation_type: input
source_metadata:
  title: Geshe Langri Thangpa Series
  language: fr
  description: 'Texts by the famous Kadampa geshe Langri Thangpa Dorje Senge (glang
    ri thang pa rdo rje seng ge, 1054–1123):'
  volume:
    c61b3b191c144f538e7663ee6bb80da9:
      title: Eight Verses of Training the Mind
      parent: Mind Training
    4eeeb26cd08f4f6d82b09fde1cbe5b56:
      title: The Sayings of Geshe Langri Tangpa
      parent: Mind Training
created_at: '2022-02-28T23:23:30.193072'
last_modified_at: '2022-02-28T23:23:30.193074'
